///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ronwell
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RonwellRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8e9d2f9e-d82b-437c-b905-80088baa92f2")]
    public partial class RonwellRepository : RepoGenBaseFolder
    {
        static RonwellRepository instance = new RonwellRepository();
        RonwellRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        RonwellRepositoryFolders.ExplorerAppFolder _explorer;
        RonwellRepositoryFolders.NewTabAppFolder _newtab;
        RonwellRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder _httpswwwtrendyolcomuyelikcbeqhttps;

        /// <summary>
        /// Gets the singleton class instance representing the RonwellRepository element repository.
        /// </summary>
        [RepositoryFolder("8e9d2f9e-d82b-437c-b905-80088baa92f2")]
        public static RonwellRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RonwellRepository() 
            : base("RonwellRepository", "/", null, 0, false, "8e9d2f9e-d82b-437c-b905-80088baa92f2", ".\\RepositoryImages\\RonwellRepository8e9d2f9e.rximgres")
        {
            _applicationundertest = new RonwellRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new RonwellRepositoryFolders.ExplorerAppFolder(this);
            _newtab = new RonwellRepositoryFolders.NewTabAppFolder(this);
            _httpswwwtrendyolcomuyelikcbeqhttps = new RonwellRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8e9d2f9e-d82b-437c-b905-80088baa92f2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("2ac68116-dc8c-48ae-b733-6dc6bce0e129")]
        public virtual RonwellRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("a5bc486a-1262-42cf-a6cd-7796125c4ec8")]
        public virtual RonwellRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The NewTab folder.
        /// </summary>
        [RepositoryFolder("bf83cbd0-1964-49ab-8158-2471725e034f")]
        public virtual RonwellRepositoryFolders.NewTabAppFolder NewTab
        {
            get { return _newtab; }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
        /// </summary>
        [RepositoryFolder("a594f409-8408-4aa2-81fe-4b04db4822c6")]
        public virtual RonwellRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder HttpsWwwTrendyolComUyelikcbEqhttps
        {
            get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RonwellRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("2ac68116-dc8c-48ae-b733-6dc6bce0e129")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _ueyeol1Info;
            RepoItemInfo _registeremailInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "2ac68116-dc8c-48ae-b733-6dc6bce0e129", "")
            {
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'account-navigation-container']/div/div[1]//div[@innertext='Üye Ol']", ".//div[#'account-navigation-container']//div[@innertext='Üye Ol']", 30000, null, "9ec64da7-4370-4e9b-a71b-c8c5da8ea8cb");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//div[#'account-navigation-container']/div/?/?/div/div/div", ".//div[#'account-navigation-container']/?/?/div/div/div/div", 30000, null, "1c46cace-1f07-4214-8c94-0c7f8baf820e");
                _ueyeol1Info = new RepoItemInfo(this, "UEyeOl1", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Üye Ol']", ".//div[#'login-register']//form/button/span[@innertext='Üye Ol']", 30000, null, "133e6d36-0bad-4067-a550-6ef288db365c");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "d387bc78-50d0-413c-a325-e3919730daf2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2ac68116-dc8c-48ae-b733-6dc6bce0e129")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2ac68116-dc8c-48ae-b733-6dc6bce0e129")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("9ec64da7-4370-4e9b-a71b-c8c5da8ea8cb")]
            public virtual Ranorex.DivTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("9ec64da7-4370-4e9b-a71b-c8c5da8ea8cb")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("1c46cace-1f07-4214-8c94-0c7f8baf820e")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("1c46cace-1f07-4214-8c94-0c7f8baf820e")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The UEyeOl1 item.
            /// </summary>
            [RepositoryItem("133e6d36-0bad-4067-a550-6ef288db365c")]
            public virtual Ranorex.SpanTag UEyeOl1
            {
                get
                {
                    return _ueyeol1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl1 item info.
            /// </summary>
            [RepositoryItemInfo("133e6d36-0bad-4067-a550-6ef288db365c")]
            public virtual RepoItemInfo UEyeOl1Info
            {
                get
                {
                    return _ueyeol1Info;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("d387bc78-50d0-413c-a325-e3919730daf2")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("d387bc78-50d0-413c-a325-e3919730daf2")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a5bc486a-1262-42cf-a6cd-7796125c4ec8")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechromeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "a5bc486a-1262-42cf-a6cd-7796125c4ec8", "")
            {
                _googlechromeInfo = new RepoItemInfo(this, "GoogleChrome", "container[@automationid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename='Google Chrome']", ".//button[@accessiblename='Google Chrome']", 30000, null, "f197e322-80b7-400a-b0f0-bb694bed73c3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a5bc486a-1262-42cf-a6cd-7796125c4ec8")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a5bc486a-1262-42cf-a6cd-7796125c4ec8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome item.
            /// </summary>
            [RepositoryItem("f197e322-80b7-400a-b0f0-bb694bed73c3")]
            public virtual Ranorex.Button GoogleChrome
            {
                get
                {
                    return _googlechromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("f197e322-80b7-400a-b0f0-bb694bed73c3")]
            public virtual RepoItemInfo GoogleChromeInfo
            {
                get
                {
                    return _googlechromeInfo;
                }
            }
        }

        /// <summary>
        /// The NewTabAppFolder folder.
        /// </summary>
        [RepositoryFolder("bf83cbd0-1964-49ab-8158-2471725e034f")]
        public partial class NewTabAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewTab  folder.
            /// </summary>
            public NewTabAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTab", "/dom[@domain='newtab']", parentFolder, 30000, null, false, "bf83cbd0-1964-49ab-8158-2471725e034f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bf83cbd0-1964-49ab-8158-2471725e034f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bf83cbd0-1964-49ab-8158-2471725e034f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder folder.
        /// </summary>
        [RepositoryFolder("a594f409-8408-4aa2-81fe-4b04db4822c6")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", "/form[@title>'https://www.trendyol.com/']", parentFolder, 30000, null, true, "a594f409-8408-4aa2-81fe-4b04db4822c6", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'https://www.trendyol.com/']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]", "?/?/container[@accessiblename='Google Chrome']/container[@accessiblerole='Pane']/container[2]/container[1]", 30000, null, "df2376fd-bad7-4c21-823e-7e80132792fc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a594f409-8408-4aa2-81fe-4b04db4822c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a594f409-8408-4aa2-81fe-4b04db4822c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("df2376fd-bad7-4c21-823e-7e80132792fc")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("df2376fd-bad7-4c21-823e-7e80132792fc")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
